/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './property-list';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/property-service-mock';
import * as import10 from 'ionic-angular/config/config';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/navbar/navbar';
import * as import15 from 'ionic-angular/components/button/button';
import * as import16 from 'ionic-angular/components/menu/menu-toggle';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from 'ionic-angular/components/icon/icon';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control_status';
import * as import22 from 'ionic-angular/components/searchbar/searchbar';
import * as import23 from 'ionic-angular/components/content/content';
import * as import24 from '@angular/common/src/directives/ng_if';
import * as import25 from 'ionic-angular/components/segment/segment';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import31 from 'ionic-angular/components/menu/menu-controller';
import * as import32 from '../../node_modules/ionic-angular/components/searchbar/searchbar.ngfactory';
import * as import33 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from '@angular/core/src/linker/template_ref';
import * as import38 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import39 from '@angular/forms/src/directives/ng_control';
import * as import40 from 'ionic-angular/components/list/list';
import * as import41 from '@angular/common/src/directives/ng_for';
import * as import42 from 'ionic-angular/gestures/gesture-controller';
import * as import43 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import44 from 'ionic-angular/components/item/item-sliding';
import * as import45 from 'ionic-angular/components/item/item';
import * as import46 from 'ionic-angular/components/thumbnail/thumbnail';
import * as import47 from '../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
import * as import48 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import49 from 'ionic-angular/util/form';
import * as import50 from '@angular/core/src/security';
var renderType_PropertyListPage_Host:import0.RenderComponentType = (null as any);
class _View_PropertyListPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PropertyListPage_0_4:import3.PropertyListPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PropertyListPage_Host0,renderType_PropertyListPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-property-list',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PropertyListPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PropertyListPage_0_4 = new import3.PropertyListPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.PropertyService),this.parentInjector.get(import10.Config));
    this._appEl_0.initComponent(this._PropertyListPage_0_4,[],compView_0);
    compView_0.create(this._PropertyListPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PropertyListPage) && (0 === requestNodeIndex))) { return this._PropertyListPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_PropertyListPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PropertyListPage_Host === (null as any))) { (renderType_PropertyListPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_PropertyListPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PropertyListPageNgFactory:import12.ComponentFactory<import3.PropertyListPage> = new import12.ComponentFactory<import3.PropertyListPage>('page-property-list',viewFactory_PropertyListPage_Host0,import3.PropertyListPage);
const styles_PropertyListPage:any[] = [];
var renderType_PropertyListPage:import0.RenderComponentType = (null as any);
class _View_PropertyListPage0 extends import1.AppView<import3.PropertyListPage> {
  _el_0:any;
  _Header_0_3:import13.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import14.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import15.Button;
  _MenuToggle_4_5:import16.MenuToggle;
  _ToolbarItem_4_6:import17.ToolbarItem;
  _query_Button_4_0:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import19.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _NgModel_9_4:import20.NgModel;
  _NgControl_9_5:any;
  _NgControlStatus_9_6:import21.NgControlStatus;
  _Searchbar_9_7:import22.Searchbar;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _Content_13_4:import23.Content;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import24.NgIf;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import24.NgIf;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _Footer_20_3:import13.Footer;
  _text_21:any;
  _el_22:any;
  _NgModel_22_3:import20.NgModel;
  _NgControl_22_4:any;
  _NgControlStatus_22_5:import21.NgControlStatus;
  _Segment_22_6:import25.Segment;
  _query_SegmentButton_22_0:import18.QueryList<any>;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _SegmentButton_24_4:import25.SegmentButton;
  _text_25:any;
  _el_26:any;
  _Icon_26_3:import19.Icon;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _SegmentButton_29_4:import25.SegmentButton;
  _text_30:any;
  _el_31:any;
  _Icon_31_3:import19.Icon;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PropertyListPage0,renderType_PropertyListPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Header(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import28.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Navbar(this.parentInjector.get(import29.App),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import30.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import15.Button('','',this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import16.MenuToggle(this.parentInjector.get(import31.MenuController),new import26.ElementRef(this._el_4),this.parentInjector.get(import27.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import17.ToolbarItem(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import19.Icon(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_4.create(this._Button_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-searchbar',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import32.viewFactory_Searchbar0(this.viewUtils,this.injector(9),this._appEl_9);
    this._NgModel_9_4 = new import20.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_9_5 = this._NgModel_9_4;
    this._NgControlStatus_9_6 = new import21.NgControlStatus(this._NgControl_9_5);
    this._Searchbar_9_7 = new import22.Searchbar(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_9),this.renderer,this._NgControl_9_5);
    this._appEl_9.initComponent(this._Searchbar_9_7,[],compView_9);
    compView_9.create(this._Searchbar_9_7,[],(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_10
      ]
      )
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_13 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','property-list');
    this._appEl_13 = new import2.AppElement(13,(null as any),this,this._el_13);
    var compView_13:any = import33.viewFactory_Content0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Content_13_4 = new import23.Content(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_13.initComponent(this._Content_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_15 = new import2.AppElement(15,13,this,this._anchor_15);
    this._TemplateRef_15_5 = new import37.TemplateRef_(this._appEl_15,viewFactory_PropertyListPage1);
    this._NgIf_15_6 = new import24.NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_17 = new import2.AppElement(17,13,this,this._anchor_17);
    this._TemplateRef_17_5 = new import37.TemplateRef_(this._appEl_17,viewFactory_PropertyListPage3);
    this._NgIf_17_6 = new import24.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_13.create(this._Content_13_4,[
      [],
      [].concat([
        this._text_14,
        this._appEl_15,
        this._text_16,
        this._appEl_17,
        this._text_18
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_20 = this.renderer.createElement(parentRenderNode,'ion-footer',(null as any));
    this.renderer.setElementAttribute(this._el_20,'padding','');
    this._Footer_20_3 = new import13.Footer(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_21 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-segment',(null as any));
    this._NgModel_22_3 = new import20.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_22_4 = this._NgModel_22_3;
    this._NgControlStatus_22_5 = new import21.NgControlStatus(this._NgControl_22_4);
    this._Segment_22_6 = new import25.Segment(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_22),this.renderer,this._NgControl_22_4);
    this._query_SegmentButton_22_0 = new import18.QueryList<any>();
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','segment-button');
    this.renderer.setElementAttribute(this._el_24,'role','button');
    this.renderer.setElementAttribute(this._el_24,'tappable','');
    this.renderer.setElementAttribute(this._el_24,'value','list');
    this._appEl_24 = new import2.AppElement(24,22,this,this._el_24);
    var compView_24:any = import38.viewFactory_SegmentButton0(this.viewUtils,this.injector(24),this._appEl_24);
    this._SegmentButton_24_4 = new import25.SegmentButton(this.renderer,new import26.ElementRef(this._el_24));
    this._appEl_24.initComponent(this._SegmentButton_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_26,'name','list');
    this.renderer.setElementAttribute(this._el_26,'role','img');
    this._Icon_26_3 = new import19.Icon(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_24.create(this._SegmentButton_24_4,[[].concat([
        this._text_25,
        this._el_26,
        this._text_27
      ]
    )],(null as any));
    this._text_28 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_22,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','segment-button');
    this.renderer.setElementAttribute(this._el_29,'role','button');
    this.renderer.setElementAttribute(this._el_29,'tappable','');
    this.renderer.setElementAttribute(this._el_29,'value','map');
    this._appEl_29 = new import2.AppElement(29,22,this,this._el_29);
    var compView_29:any = import38.viewFactory_SegmentButton0(this.viewUtils,this.injector(29),this._appEl_29);
    this._SegmentButton_29_4 = new import25.SegmentButton(this.renderer,new import26.ElementRef(this._el_29));
    this._appEl_29.initComponent(this._SegmentButton_29_4,[],compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_31,'name','map');
    this.renderer.setElementAttribute(this._el_31,'role','img');
    this._Icon_31_3 = new import19.Icon(this.parentInjector.get(import10.Config),new import26.ElementRef(this._el_31),this.renderer);
    this._text_32 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_29.create(this._SegmentButton_29_4,[[].concat([
        this._text_30,
        this._el_31,
        this._text_32
      ]
    )],(null as any));
    this._text_33 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_20,'\n',(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'ngModelChange',this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_9,'ionInput',this.eventHandler(this._handle_ionInput_9_1.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_9,'ionCancel',this.eventHandler(this._handle_ionCancel_9_2.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_9_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    const subscription_1:any = this._Searchbar_9_7.ionInput.subscribe(this.eventHandler(this._handle_ionInput_9_1.bind(this)));
    const subscription_2:any = this._Searchbar_9_7.ionCancel.subscribe(this.eventHandler(this._handle_ionCancel_9_2.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_22,'ngModelChange',this.eventHandler(this._handle_ngModelChange_22_0.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    const subscription_3:any = this._NgModel_22_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_22_0.bind(this)));
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_29,'ionSelect',this.eventHandler(this._handle_ionSelect_29_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_1.bind(this)));
    this._expr_40 = import7.UNINITIALIZED;
    const subscription_4:any = this._SegmentButton_29_4.ionSelect.subscribe(this.eventHandler(this._handle_ionSelect_29_0.bind(this)));
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import15.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import16.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import17.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import20.NgModel) && (9 === requestNodeIndex))) { return this._NgModel_9_4; }
    if (((token === import39.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_5; }
    if (((token === import21.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_6; }
    if (((token === import22.Searchbar) && (9 === requestNodeIndex))) { return this._Searchbar_9_7; }
    if (((token === import14.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Navbar_2_4; }
    if (((token === import13.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Header_0_3; }
    if (((token === import37.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import24.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6; }
    if (((token === import37.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import24.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    if (((token === import23.Content) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Content_13_4; }
    if (((token === import19.Icon) && (26 === requestNodeIndex))) { return this._Icon_26_3; }
    if (((token === import25.SegmentButton) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._SegmentButton_24_4; }
    if (((token === import19.Icon) && (31 === requestNodeIndex))) { return this._Icon_31_3; }
    if (((token === import25.SegmentButton) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._SegmentButton_29_4; }
    if (((token === import20.NgModel) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._NgModel_22_3; }
    if (((token === import39.NgControl) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._NgControl_22_4; }
    if (((token === import21.NgControlStatus) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._NgControlStatus_22_5; }
    if (((token === import25.Segment) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Segment_22_6; }
    if (((token === import13.Footer) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Footer_20_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    changes = (null as any);
    const currVal_10:any = this.context.searchKey;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgModel_9_4.model = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgModel_9_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Searchbar_9_7.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_13_4.ngOnInit(); }
    const currVal_24:any = (this.context.viewMode === 'list');
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgIf_15_6.ngIf = currVal_24;
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = (this.context.viewMode === 'map');
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgIf_17_6.ngIf = currVal_25;
      this._expr_25 = currVal_25;
    }
    changes = (null as any);
    const currVal_27:any = this.context.viewMode;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgModel_22_3.model = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    if ((changes !== (null as any))) { this._NgModel_22_3.ngOnChanges(changes); }
    const currVal_35:any = 'list';
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._SegmentButton_24_4.value = currVal_35;
      this._expr_35 = currVal_35;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_24_4.ngOnInit(); }
    const currVal_36:any = 'list';
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._Icon_26_3.name = currVal_36;
      this._expr_36 = currVal_36;
    }
    const currVal_40:any = 'map';
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this._SegmentButton_29_4.value = currVal_40;
      this._expr_40 = currVal_40;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_29_4.ngOnInit(); }
    const currVal_41:any = 'map';
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this._Icon_31_3.name = currVal_41;
      this._expr_41 = currVal_41;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_SegmentButton_22_0.dirty) {
        this._query_SegmentButton_22_0.reset([
          this._SegmentButton_24_4,
          this._SegmentButton_29_4
        ]
        );
        this._Segment_22_6._buttons = this._query_SegmentButton_22_0;
        this._query_SegmentButton_22_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_9_7.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_11:any = this._NgControlStatus_9_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_9,'ng-untouched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_9_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_9,'ng-touched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_9_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_9,'ng-pristine',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_9_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_9,'ng-dirty',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_9_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_9,'ng-valid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_9_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_9,'ng-invalid',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._Searchbar_9_7.animated;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_9,'searchbar-animated',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._Searchbar_9_7._value;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_9,'searchbar-has-value',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._Searchbar_9_7._isActive;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_9,'searchbar-active',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._Searchbar_9_7.showCancelButton;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_9,'searchbar-show-cancel',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._Searchbar_9_7._shouldAlignLeft;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_9,'searchbar-left-aligned',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._Searchbar_9_7._sbHasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_9,'searchbar-has-focus',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._Content_13_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_13,'statusbar-padding',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_28:any = this._NgControlStatus_22_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_22,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_22_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_22,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_22_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_22,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_22_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_22,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_22_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_22,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_22_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_22,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_37:any = this._Icon_26_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_26,'hide',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_42:any = this._Icon_31_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_31,'hide',currVal_42);
      this._expr_42 = currVal_42;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Segment_22_6.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._NgModel_9_4.ngOnDestroy();
    this._Content_13_4.ngOnDestroy();
    this._Icon_26_3.ngOnDestroy();
    this._Icon_31_3.ngOnDestroy();
    this._NgModel_22_3.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.searchKey = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_9_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onInput($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionCancel_9_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onCancel($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.viewMode = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this._appEl_24.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_24_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_ionSelect_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.showMap()) !== false);
    return (true && pd_0);
  }
  private _handle_click_29_1($event:any):boolean {
    this._appEl_29.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_29_4.onClick()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PropertyListPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PropertyListPage> {
  if ((renderType_PropertyListPage === (null as any))) { (renderType_PropertyListPage = viewUtils.createRenderComponentType('C:/Users/guojin/Desktop/server/iv/.tmp/pages/property-list/property-list.html',0,import11.ViewEncapsulation.None,styles_PropertyListPage,{})); }
  return new _View_PropertyListPage0(viewUtils,parentInjector,declarationEl);
}
class _View_PropertyListPage1 extends import1.AppView<any> {
  _el_0:any;
  _List_0_3:import40.List;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import41.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PropertyListPage1,renderType_PropertyListPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_0_3 = new import40.List(this.parent.parentInjector.get(import10.Config),new import26.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import42.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import37.TemplateRef_(this._appEl_2,viewFactory_PropertyListPage2);
    this._NgFor_2_6 = new import41.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import43.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import41.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    if (((token === import40.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._List_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.properties;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PropertyListPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PropertyListPage1(viewUtils,parentInjector,declarationEl);
}
class _View_PropertyListPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemSliding_0_4:import44.ItemSliding;
  _query_Item_0_0:import18.QueryList<any>;
  _query_ItemOptions_0_1:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import45.Item;
  _ItemContent_2_5:import45.ItemContent;
  _query_Label_2_0:import18.QueryList<any>;
  _query_Button_2_1:import18.QueryList<any>;
  _query_Icon_2_2:import18.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Thumbnail_4_3:import46.Thumbnail;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _ItemOptions_16_3:import44.ItemOptions;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PropertyListPage2,renderType_PropertyListPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import47.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import44.ItemSliding((<_View_PropertyListPage1>this.parent)._List_0_3,this.renderer,new import26.ElementRef(this._el_0),this.parent.parent.parentInjector.get(import35.NgZone));
    this._query_Item_0_0 = new import18.QueryList<any>();
    this._query_ItemOptions_0_1 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import48.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import45.Item(this.parent.parent.parentInjector.get(import49.Form),this.parent.parent.parentInjector.get(import10.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import45.ItemContent();
    this._query_Label_2_0 = new import18.QueryList<any>();
    this._query_Button_2_1 = new import18.QueryList<any>();
    this._query_Icon_2_2 = new import18.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Thumbnail_4_3 = new import46.Thumbnail();
    this._text_5 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [].concat([this._el_4]),
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11,
        this._el_12,
        this._text_14
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this._ItemOptions_16_3 = new import44.ItemOptions(new import26.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'danger','');
    this._text_19 = this.renderer.createText(this._el_18,'Delete',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4]);
    this._ItemSliding_0_4.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4,[
      [].concat([this._el_2]),
      [].concat([this._el_16])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Thumbnail) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Thumbnail_4_3; }
    if (((token === import45.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Item_2_4; }
    if (((token === import45.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemContent_2_5; }
    if (((token === import44.ItemOptions) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ItemOptions_16_3; }
    if (((token === import44.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemSliding_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([this._ItemOptions_16_3]);
        this._ItemSliding_0_4._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.thumb,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import50.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(3,'',this.context.$implicit.city,', ',this.context.$implicit.state,' ∙ ',this.context.$implicit.price,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_13,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.openPropertyDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.deleteItem(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PropertyListPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PropertyListPage2(viewUtils,parentInjector,declarationEl);
}
class _View_PropertyListPage3 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PropertyListPage3,renderType_PropertyListPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','map');
    this.renderer.setElementAttribute(this._el_0,'style','width:100%;height:100%;');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_PropertyListPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PropertyListPage3(viewUtils,parentInjector,declarationEl);
}