var brokers = [
    {
        id: 1,
        firstName: "Nino",
        lastName: "F",
        title: "Pious Mage",
        hp: 16,
        atk: 20,
        spd: 10,
        def: 4,
        res: 7,
        hpm: 33,
        atkm: 46,
        spdm: 36,
        defm: 19,
        resm: 29,
        artby: "Amagaitaro (アマガイタロー)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "caroline@ionicrealty.com",
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/caroline_kingsley.jpg"
    },
    {
        id: 2,
        firstName: "Lucina",
        lastName: "F",
        title: "Future Witness",
        hp: 19,
        atk: 24,
        spd: 10,
        def: 6,
        res: 4,
        hpm: 43,
        atkm: 50,
        spdm: 36,
        defm: 25,
        resm: 19,
        artby: "Maiponpon (まいぽんぽん)  / INTELLIGENT SYSTEMS",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "michael@ionicrealty.com",
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/michael_jones.jpg"
    },
    {
        id: 3,
        firstName: "Hector",
        lastName: "M",
        title: "General of Ostia",
        hp: 24,
        atk: 26,
        spd: 5,
        def: 11,
        res: 4,
        hpm: 52,
        atkm: 52,
        spdm: 24,
        defm: 37,
        resm: 19,
        artby: "AKIRA",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "jonathan@ionicrealty.com",
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/jonathan_bradley.jpg"
    },
    {
        id: 4,
        firstName: "Takumi",
        lastName: "M",
        title: "Wild Card",
        hp: 18,
        atk: 22,
        spd: 7,
        def: 6,
        res: 5,
        hpm: 40,
        atkm: 46,
        spdm: 33,
        defm: 25,
        resm: 18,
        artby: "Hino Shinnosuke (日野慎之助)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "jen@ionicrealty.com",
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/jennifer_wu.jpg"
    },
    {
        id: 5,
        firstName: "Linde",
        lastName: "F",
        title: "Light Mage",
        hp: 16,
        atk: 23,
        spd: 10,
        def: 4,
        res: 5,
        hpm: 35,
        atkm: 49,
        spdm: 39,
        defm: 14,
        resm: 27,
        artby: "Kippu (切符)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "olivia@ionicrealty.com",
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/olivia_green.jpg"
    },
    {
        id: 6,
        firstName: "Ninian",
        lastName: "F",
        title: "Oracle of Destiny",
        hp: 16,
        atk: 18,
        spd: 7,
        def: 6,
        res: 5,
        hpm: 42,
        atkm: 37,
        spdm: 33,
        defm: 23,
        resm: 27,
        artby: "Kippu (切符)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "miriam@ionicrealty.com",
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/miriam_aupont.jpg"
    },
    {
        id: 7,
        firstName: "Jaffar",
        lastName: "M",
        title: "Angel of Death",
        hp: 17,
        atk: 18,
        spd: 9,
        def: 6,
        res: 5,
        hpm: 41,
        atkm: 42,
        spdm: 38,
        defm: 20,
        resm: 17,
        artby: "Kusugi Toku (久杉トク)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "michelle@ionicrealty.com",
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/michelle_lambert.jpg"
    },
    {
        id: 8,
        firstName: "Tharja",
        lastName: "F",
        title: "Dark Shadow",
        hp: 17,
        atk: 21,
        spd: 8,
        def: 6,
        res: 5,
        hpm: 39,
        atkm: 45,
        spdm: 34,
        defm: 23,
        resm: 20,
        artby: "ZIS",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        picture: "https://s3-us-west-1.amazonaws.com/sfdc-demo/people/victor_ochoa.jpg"
    }
];
export default brokers;
//# sourceMappingURL=mock-brokers.js.map