/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './broker-detail';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from 'ionic-angular/navigation/nav-params';
import * as import11 from '../../providers/broker-service-mock';
import * as import12 from 'ionic-angular/components/toast/toast';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from 'ionic-angular/components/toolbar/toolbar';
import * as import16 from 'ionic-angular/components/navbar/navbar';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from 'ionic-angular/components/card/card';
import * as import20 from 'ionic-angular/components/item/item';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from 'ionic-angular/components/icon/icon';
import * as import23 from 'ionic-angular/components/list/list';
import * as import24 from 'ionic-angular/components/button/button';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from 'ionic-angular/gestures/gesture-controller';
import * as import38 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import39 from '@angular/core/src/security';
var renderType_BrokerDetailPage_Host:import0.RenderComponentType = (null as any);
class _View_BrokerDetailPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _BrokerDetailPage_0_4:import3.BrokerDetailPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BrokerDetailPage_Host0,renderType_BrokerDetailPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-broker-detail',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_BrokerDetailPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._BrokerDetailPage_0_4 = new import3.BrokerDetailPage(this.parentInjector.get(import8.ActionSheetController),this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.NavParams),this.parentInjector.get(import11.BrokerService),this.parentInjector.get(import12.ToastController));
    this._appEl_0.initComponent(this._BrokerDetailPage_0_4,[],compView_0);
    compView_0.create(this._BrokerDetailPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.BrokerDetailPage) && (0 === requestNodeIndex))) { return this._BrokerDetailPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_BrokerDetailPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_BrokerDetailPage_Host === (null as any))) { (renderType_BrokerDetailPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_BrokerDetailPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const BrokerDetailPageNgFactory:import14.ComponentFactory<import3.BrokerDetailPage> = new import14.ComponentFactory<import3.BrokerDetailPage>('page-broker-detail',viewFactory_BrokerDetailPage_Host0,import3.BrokerDetailPage);
const styles_BrokerDetailPage:any[] = [];
var renderType_BrokerDetailPage:import0.RenderComponentType = (null as any);
class _View_BrokerDetailPage0 extends import1.AppView<import3.BrokerDetailPage> {
  _el_0:any;
  _Header_0_3:import15.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import16.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import17.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import18.Content;
  _text_10:any;
  _el_11:any;
  _Card_11_3:import19.Card;
  _text_12:any;
  _el_13:any;
  _CardContent_13_3:import19.CardContent;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _Item_24_4:import20.Item;
  _ItemContent_24_5:import20.ItemContent;
  _query_Label_24_0:import21.QueryList<any>;
  _query_Button_24_1:import21.QueryList<any>;
  _query_Icon_24_2:import21.QueryList<any>;
  _el_25:any;
  _Icon_25_3:import22.Icon;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _List_28_3:import23.List;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _Item_30_4:import20.Item;
  _ItemContent_30_5:import20.ItemContent;
  _query_Label_30_0:import21.QueryList<any>;
  _query_Button_30_1:import21.QueryList<any>;
  _query_Icon_30_2:import21.QueryList<any>;
  _text_31:any;
  _el_32:any;
  _Icon_32_3:import22.Icon;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import2.AppElement;
  _Item_42_4:import20.Item;
  _ItemContent_42_5:import20.ItemContent;
  _query_Label_42_0:import21.QueryList<any>;
  _query_Button_42_1:import21.QueryList<any>;
  _query_Icon_42_2:import21.QueryList<any>;
  _text_43:any;
  _el_44:any;
  _Icon_44_3:import22.Icon;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import2.AppElement;
  _Item_54_4:import20.Item;
  _ItemContent_54_5:import20.ItemContent;
  _query_Label_54_0:import21.QueryList<any>;
  _query_Button_54_1:import21.QueryList<any>;
  _query_Icon_54_2:import21.QueryList<any>;
  _text_55:any;
  _el_56:any;
  _Icon_56_3:import22.Icon;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  /*private*/ _appEl_66:import2.AppElement;
  _Item_66_4:import20.Item;
  _ItemContent_66_5:import20.ItemContent;
  _query_Label_66_0:import21.QueryList<any>;
  _query_Button_66_1:import21.QueryList<any>;
  _query_Icon_66_2:import21.QueryList<any>;
  _text_67:any;
  _el_68:any;
  _Icon_68_3:import22.Icon;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  /*private*/ _appEl_78:import2.AppElement;
  _Item_78_4:import20.Item;
  _ItemContent_78_5:import20.ItemContent;
  _query_Label_78_0:import21.QueryList<any>;
  _query_Button_78_1:import21.QueryList<any>;
  _query_Icon_78_2:import21.QueryList<any>;
  _text_79:any;
  _el_80:any;
  _Icon_80_3:import22.Icon;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _el_91:any;
  /*private*/ _appEl_91:import2.AppElement;
  _Item_91_4:import20.Item;
  _ItemContent_91_5:import20.ItemContent;
  _query_Label_91_0:import21.QueryList<any>;
  _query_Button_91_1:import21.QueryList<any>;
  _query_Icon_91_2:import21.QueryList<any>;
  _text_92:any;
  _el_93:any;
  /*private*/ _appEl_93:import2.AppElement;
  _Button_93_4:import24.Button;
  _text_94:any;
  _el_95:any;
  _Icon_95_3:import22.Icon;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  /*private*/ _appEl_98:import2.AppElement;
  _Button_98_4:import24.Button;
  _text_99:any;
  _el_100:any;
  _Icon_100_3:import22.Icon;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_BrokerDetailPage0,renderType_BrokerDetailPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Header(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import28.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Navbar(this.parentInjector.get(import29.App),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import30.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.ToolbarTitle(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import15.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Heroes',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','broker');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import31.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import18.Content(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_11_3 = new import19.Card(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText(this._el_11,'\n\n       \n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-card-content',(null as any));
    this._CardContent_13_3 = new import19.CardContent();
    this._text_14 = this.renderer.createText(this._el_13,'\n             \n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'img',(null as any));
    this._text_16 = this.renderer.createText(this._el_13,'\n              \n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_13,'h2',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_13,'h3',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n         \n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this.renderer.setElementAttribute(this._el_24,'ion-item','');
    this._appEl_24 = new import2.AppElement(24,11,this,this._el_24);
    var compView_24:any = import35.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import20.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_24),this.renderer);
    this._ItemContent_24_5 = new import20.ItemContent();
    this._query_Label_24_0 = new import21.QueryList<any>();
    this._query_Button_24_1 = new import21.QueryList<any>();
    this._query_Icon_24_2 = new import21.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4,[],compView_24);
    this._el_25 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_25,'item-left','');
    this.renderer.setElementAttribute(this._el_25,'name','brush');
    this.renderer.setElementAttribute(this._el_25,'role','img');
    this._Icon_25_3 = new import22.Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_24_0.reset([]);
    this._Item_24_4.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4,[
      [].concat([this._el_25]),
      [],
      [].concat([this._text_26]),
      [],
      []
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_11,' \n        \n\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_11,'ion-list',(null as any));
    this._List_28_3 = new import23.List(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_28),this.renderer,this.parentInjector.get(import37.GestureController));
    this._text_29 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','item item-block');
    this.renderer.setElementAttribute(this._el_30,'href','tel:');
    this.renderer.setElementAttribute(this._el_30,'ion-item','');
    this._appEl_30 = new import2.AppElement(30,28,this,this._el_30);
    var compView_30:any = import35.viewFactory_Item0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Item_30_4 = new import20.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_30),this.renderer);
    this._ItemContent_30_5 = new import20.ItemContent();
    this._query_Label_30_0 = new import21.QueryList<any>();
    this._query_Button_30_1 = new import21.QueryList<any>();
    this._query_Icon_30_2 = new import21.QueryList<any>();
    this._appEl_30.initComponent(this._Item_30_4,[],compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_32,'item-left','');
    this.renderer.setElementAttribute(this._el_32,'name','');
    this.renderer.setElementAttribute(this._el_32,'role','img');
    this._Icon_32_3 = new import22.Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_32),this.renderer);
    this._text_33 = this.renderer.createText(this._el_32,'HP ',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'LV.1',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_30_0.reset([]);
    this._Item_30_4.contentLabel = this._query_Label_30_0.first;
    compView_30.create(this._Item_30_4,[
      [].concat([this._el_32]),
      [],
      [].concat([
        this._text_31,
        this._text_34,
        this._el_35,
        this._text_37,
        this._el_38,
        this._text_40
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','item item-block');
    this.renderer.setElementAttribute(this._el_42,'href','tel:');
    this.renderer.setElementAttribute(this._el_42,'ion-item','');
    this._appEl_42 = new import2.AppElement(42,28,this,this._el_42);
    var compView_42:any = import35.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Item_42_4 = new import20.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_42),this.renderer);
    this._ItemContent_42_5 = new import20.ItemContent();
    this._query_Label_42_0 = new import21.QueryList<any>();
    this._query_Button_42_1 = new import21.QueryList<any>();
    this._query_Icon_42_2 = new import21.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_4,[],compView_42);
    this._text_43 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_44,'item-left','');
    this.renderer.setElementAttribute(this._el_44,'name','');
    this.renderer.setElementAttribute(this._el_44,'role','img');
    this._Icon_44_3 = new import22.Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_44),this.renderer);
    this._text_45 = this.renderer.createText(this._el_44,'ATK',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'LV.1',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_42_0.reset([]);
    this._Item_42_4.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_4,[
      [].concat([this._el_44]),
      [],
      [].concat([
        this._text_43,
        this._text_46,
        this._el_47,
        this._text_49,
        this._el_50,
        this._text_52
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_53 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','item item-block');
    this.renderer.setElementAttribute(this._el_54,'href','tel:');
    this.renderer.setElementAttribute(this._el_54,'ion-item','');
    this._appEl_54 = new import2.AppElement(54,28,this,this._el_54);
    var compView_54:any = import35.viewFactory_Item0(this.viewUtils,this.injector(54),this._appEl_54);
    this._Item_54_4 = new import20.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_54),this.renderer);
    this._ItemContent_54_5 = new import20.ItemContent();
    this._query_Label_54_0 = new import21.QueryList<any>();
    this._query_Button_54_1 = new import21.QueryList<any>();
    this._query_Icon_54_2 = new import21.QueryList<any>();
    this._appEl_54.initComponent(this._Item_54_4,[],compView_54);
    this._text_55 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_56,'item-left','');
    this.renderer.setElementAttribute(this._el_56,'name','');
    this.renderer.setElementAttribute(this._el_56,'role','img');
    this._Icon_56_3 = new import22.Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_56),this.renderer);
    this._text_57 = this.renderer.createText(this._el_56,'SPD',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_59 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'LV.1',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'',(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_54_0.reset([]);
    this._Item_54_4.contentLabel = this._query_Label_54_0.first;
    compView_54.create(this._Item_54_4,[
      [].concat([this._el_56]),
      [],
      [].concat([
        this._text_55,
        this._text_58,
        this._el_59,
        this._text_61,
        this._el_62,
        this._text_64
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_65 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','item item-block');
    this.renderer.setElementAttribute(this._el_66,'href','tel:');
    this.renderer.setElementAttribute(this._el_66,'ion-item','');
    this._appEl_66 = new import2.AppElement(66,28,this,this._el_66);
    var compView_66:any = import35.viewFactory_Item0(this.viewUtils,this.injector(66),this._appEl_66);
    this._Item_66_4 = new import20.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_66),this.renderer);
    this._ItemContent_66_5 = new import20.ItemContent();
    this._query_Label_66_0 = new import21.QueryList<any>();
    this._query_Button_66_1 = new import21.QueryList<any>();
    this._query_Icon_66_2 = new import21.QueryList<any>();
    this._appEl_66.initComponent(this._Item_66_4,[],compView_66);
    this._text_67 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_68 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_68,'item-left','');
    this.renderer.setElementAttribute(this._el_68,'name','');
    this.renderer.setElementAttribute(this._el_68,'role','img');
    this._Icon_68_3 = new import22.Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_68),this.renderer);
    this._text_69 = this.renderer.createText(this._el_68,'DEF',(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'LV.1',(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_74 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'',(null as any));
    this._text_76 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_66_0.reset([]);
    this._Item_66_4.contentLabel = this._query_Label_66_0.first;
    compView_66.create(this._Item_66_4,[
      [].concat([this._el_68]),
      [],
      [].concat([
        this._text_67,
        this._text_70,
        this._el_71,
        this._text_73,
        this._el_74,
        this._text_76
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_77 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_78,'class','item item-block');
    this.renderer.setElementAttribute(this._el_78,'href','tel:');
    this.renderer.setElementAttribute(this._el_78,'ion-item','');
    this._appEl_78 = new import2.AppElement(78,28,this,this._el_78);
    var compView_78:any = import35.viewFactory_Item0(this.viewUtils,this.injector(78),this._appEl_78);
    this._Item_78_4 = new import20.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_78),this.renderer);
    this._ItemContent_78_5 = new import20.ItemContent();
    this._query_Label_78_0 = new import21.QueryList<any>();
    this._query_Button_78_1 = new import21.QueryList<any>();
    this._query_Icon_78_2 = new import21.QueryList<any>();
    this._appEl_78.initComponent(this._Item_78_4,[],compView_78);
    this._text_79 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_80 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_80,'item-left','');
    this.renderer.setElementAttribute(this._el_80,'name','');
    this.renderer.setElementAttribute(this._el_80,'role','img');
    this._Icon_80_3 = new import22.Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_80),this.renderer);
    this._text_81 = this.renderer.createText(this._el_80,'RES',(null as any));
    this._text_82 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_83 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'LV.1',(null as any));
    this._text_85 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_86 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'',(null as any));
    this._text_88 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_78_0.reset([]);
    this._Item_78_4.contentLabel = this._query_Label_78_0.first;
    compView_78.create(this._Item_78_4,[
      [].concat([this._el_80]),
      [],
      [].concat([
        this._text_79,
        this._text_82,
        this._el_83,
        this._text_85,
        this._el_86,
        this._text_88
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_89 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._text_90 = this.renderer.createText(this._el_11,'\n\n         ',(null as any));
    this._el_91 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_91,'class','item item-block');
    this._appEl_91 = new import2.AppElement(91,11,this,this._el_91);
    var compView_91:any = import35.viewFactory_Item0(this.viewUtils,this.injector(91),this._appEl_91);
    this._Item_91_4 = new import20.Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_91),this.renderer);
    this._ItemContent_91_5 = new import20.ItemContent();
    this._query_Label_91_0 = new import21.QueryList<any>();
    this._query_Button_91_1 = new import21.QueryList<any>();
    this._query_Icon_91_2 = new import21.QueryList<any>();
    this._appEl_91.initComponent(this._Item_91_4,[],compView_91);
    this._text_92 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_93 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_93,'clear','');
    this.renderer.setElementAttribute(this._el_93,'icon-left','');
    this.renderer.setElementAttribute(this._el_93,'ion-button','');
    this.renderer.setElementAttribute(this._el_93,'item-left','');
    this._appEl_93 = new import2.AppElement(93,91,this,this._el_93);
    var compView_93:any = import38.viewFactory_Button0(this.viewUtils,this.injector(93),this._appEl_93);
    this._Button_93_4 = new import24.Button((null as any),'',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_93),this.renderer);
    this._appEl_93.initComponent(this._Button_93_4,[],compView_93);
    this._text_94 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_95 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_95,'name','star');
    this.renderer.setElementAttribute(this._el_95,'role','img');
    this._Icon_95_3 = new import22.Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_95),this.renderer);
    this._text_96 = this.renderer.createText((null as any),'\n                Favorite\n            ',(null as any));
      compView_93.create(this._Button_93_4,[[].concat([
        this._text_94,
        this._el_95,
        this._text_96
      ]
    )],(null as any));
    this._text_97 = this.renderer.createText((null as any),'\n\n              ',(null as any));
    this._el_98 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_98,'clear','');
    this.renderer.setElementAttribute(this._el_98,'icon-left','');
    this.renderer.setElementAttribute(this._el_98,'ion-button','');
    this.renderer.setElementAttribute(this._el_98,'item-right','');
    this._appEl_98 = new import2.AppElement(98,91,this,this._el_98);
    var compView_98:any = import38.viewFactory_Button0(this.viewUtils,this.injector(98),this._appEl_98);
    this._Button_98_4 = new import24.Button((null as any),'',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_98),this.renderer);
    this._appEl_98.initComponent(this._Button_98_4,[],compView_98);
    this._text_99 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_100 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_100,'name','star');
    this.renderer.setElementAttribute(this._el_100,'role','img');
    this._Icon_100_3 = new import22.Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_100),this.renderer);
    this._text_101 = this.renderer.createText((null as any),'\n                LV.40\n            ',(null as any));
      compView_98.create(this._Button_98_4,[[].concat([
        this._text_99,
        this._el_100,
        this._text_101
      ]
    )],(null as any));
    this._text_102 = this.renderer.createText((null as any),'\n\n             ',(null as any));
    this._query_Label_91_0.reset([]);
    this._Item_91_4.contentLabel = this._query_Label_91_0.first;
    compView_91.create(this._Item_91_4,[
      [].concat([this._el_93]),
      [],
      [].concat([
        this._text_92,
        this._text_97,
        this._text_102
      ]
      ),
      [],
      [].concat([this._el_98])
    ]
    ,(null as any));
    this._text_103 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_104 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_104
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_105 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_93,'click',this.eventHandler(this._handle_click_93_0.bind(this)));
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_98,'click',this.eventHandler(this._handle_click_98_0.bind(this)));
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import16.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import15.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import19.CardContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._CardContent_13_3; }
    if (((token === import22.Icon) && (25 === requestNodeIndex))) { return this._Icon_25_3; }
    if (((token === import20.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_24_4; }
    if (((token === import20.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_24_5; }
    if (((token === import22.Icon) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Icon_32_3; }
    if (((token === import20.Item) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_30_4; }
    if (((token === import20.ItemContent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_30_5; }
    if (((token === import22.Icon) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Icon_44_3; }
    if (((token === import20.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Item_42_4; }
    if (((token === import20.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._ItemContent_42_5; }
    if (((token === import22.Icon) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Icon_56_3; }
    if (((token === import20.Item) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Item_54_4; }
    if (((token === import20.ItemContent) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._ItemContent_54_5; }
    if (((token === import22.Icon) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Icon_68_3; }
    if (((token === import20.Item) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._Item_66_4; }
    if (((token === import20.ItemContent) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._ItemContent_66_5; }
    if (((token === import22.Icon) && ((80 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Icon_80_3; }
    if (((token === import20.Item) && ((78 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._Item_78_4; }
    if (((token === import20.ItemContent) && ((78 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._ItemContent_78_5; }
    if (((token === import23.List) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._List_28_3; }
    if (((token === import22.Icon) && (95 === requestNodeIndex))) { return this._Icon_95_3; }
    if (((token === import24.Button) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 96)))) { return this._Button_93_4; }
    if (((token === import22.Icon) && (100 === requestNodeIndex))) { return this._Icon_100_3; }
    if (((token === import24.Button) && ((98 <= requestNodeIndex) && (requestNodeIndex <= 101)))) { return this._Button_98_4; }
    if (((token === import20.Item) && ((91 <= requestNodeIndex) && (requestNodeIndex <= 102)))) { return this._Item_91_4; }
    if (((token === import20.ItemContent) && ((91 <= requestNodeIndex) && (requestNodeIndex <= 102)))) { return this._ItemContent_91_5; }
    if (((token === import19.Card) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 103)))) { return this._Card_11_3; }
    if (((token === import18.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 104)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_7:any = 'brush';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_25_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_32_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_13:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Icon_44_3.name = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Icon_56_3.name = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_19:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Icon_68_3.name = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_22:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._Icon_80_3.name = currVal_22;
      this._expr_22 = currVal_22;
    }
    changed = false;
    const currVal_26:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._Button_93_4.clear = currVal_26;
      changed = true;
      this._expr_26 = currVal_26;
    }
    if (changed) { this._appEl_93.componentView.markAsCheckOnce(); }
    const currVal_27:any = 'star';
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._Icon_95_3.name = currVal_27;
      this._expr_27 = currVal_27;
    }
    changed = false;
    const currVal_30:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._Button_98_4.clear = currVal_30;
      changed = true;
      this._expr_30 = currVal_30;
    }
    if (changed) { this._appEl_98.componentView.markAsCheckOnce(); }
    const currVal_31:any = 'star';
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._Icon_100_3.name = currVal_31;
      this._expr_31 = currVal_31;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset([]);
        this._Item_24_4._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset([this._Icon_25_3]);
        this._Item_24_4._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_30_1.dirty) {
        this._query_Button_30_1.reset([]);
        this._Item_30_4._buttons = this._query_Button_30_1;
        this._query_Button_30_1.notifyOnChanges();
      }
      if (this._query_Icon_30_2.dirty) {
        this._query_Icon_30_2.reset([this._Icon_32_3]);
        this._Item_30_4._icons = this._query_Icon_30_2;
        this._query_Icon_30_2.notifyOnChanges();
      }
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset([]);
        this._Item_42_4._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset([this._Icon_44_3]);
        this._Item_42_4._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      if (this._query_Button_54_1.dirty) {
        this._query_Button_54_1.reset([]);
        this._Item_54_4._buttons = this._query_Button_54_1;
        this._query_Button_54_1.notifyOnChanges();
      }
      if (this._query_Icon_54_2.dirty) {
        this._query_Icon_54_2.reset([this._Icon_56_3]);
        this._Item_54_4._icons = this._query_Icon_54_2;
        this._query_Icon_54_2.notifyOnChanges();
      }
      if (this._query_Button_66_1.dirty) {
        this._query_Button_66_1.reset([]);
        this._Item_66_4._buttons = this._query_Button_66_1;
        this._query_Button_66_1.notifyOnChanges();
      }
      if (this._query_Icon_66_2.dirty) {
        this._query_Icon_66_2.reset([this._Icon_68_3]);
        this._Item_66_4._icons = this._query_Icon_66_2;
        this._query_Icon_66_2.notifyOnChanges();
      }
      if (this._query_Button_78_1.dirty) {
        this._query_Button_78_1.reset([]);
        this._Item_78_4._buttons = this._query_Button_78_1;
        this._query_Button_78_1.notifyOnChanges();
      }
      if (this._query_Icon_78_2.dirty) {
        this._query_Icon_78_2.reset([this._Icon_80_3]);
        this._Item_78_4._icons = this._query_Icon_78_2;
        this._query_Icon_78_2.notifyOnChanges();
      }
      if (this._query_Button_91_1.dirty) {
        this._query_Button_91_1.reset([
          this._Button_93_4,
          this._Button_98_4
        ]
        );
        this._Item_91_4._buttons = this._query_Button_91_1;
        this._query_Button_91_1.notifyOnChanges();
      }
      if (this._query_Icon_91_2.dirty) {
        this._query_Icon_91_2.reset([]);
        this._Item_91_4._icons = this._query_Icon_91_2;
        this._query_Icon_91_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_24_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_30_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_42_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_54_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_66_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_78_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_93_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_98_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_91_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(2,'./Face/',this.context.broker.firstName,'',this.context.broker.lastName,'/Face_FC.png');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_15,'src',this.viewUtils.sanitizer.sanitize(import39.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(2,'',this.context.broker.firstName,' ',this.context.broker.lastName,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_18,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.broker.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_21,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._Icon_25_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_25,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.broker.artby,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_26,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = this._Icon_32_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_32,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import4.interpolate(1,'',this.context.broker.hp,'');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_39,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._Icon_44_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_44,'hide',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = import4.interpolate(1,'',this.context.broker.atk,'');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_51,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = this._Icon_56_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_56,'hide',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = import4.interpolate(1,'',this.context.broker.spd,'');
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_63,currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_20:any = this._Icon_68_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_68,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = import4.interpolate(1,'',this.context.broker.def,'');
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_75,currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_23:any = this._Icon_80_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_80,'hide',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = import4.interpolate(1,'',this.context.broker.res,'');
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setText(this._text_87,currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_28:any = this._Icon_95_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_95,'hide',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_32:any = this._Icon_100_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_100,'hide',currVal_32);
      this._expr_32 = currVal_32;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_25_3.ngOnDestroy();
    this._Icon_32_3.ngOnDestroy();
    this._Icon_44_3.ngOnDestroy();
    this._Icon_56_3.ngOnDestroy();
    this._Icon_68_3.ngOnDestroy();
    this._Icon_80_3.ngOnDestroy();
    this._Icon_95_3.ngOnDestroy();
    this._Icon_100_3.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.openArts(this.context.broker)) !== false);
    return (true && pd_0);
  }
  private _handle_click_93_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.favorite(this.context.broker)) !== false);
    return (true && pd_0);
  }
  private _handle_click_98_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.share(this.context.broker)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_BrokerDetailPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.BrokerDetailPage> {
  if ((renderType_BrokerDetailPage === (null as any))) { (renderType_BrokerDetailPage = viewUtils.createRenderComponentType('C:/Users/guojin/Desktop/server/iv/.tmp/pages/broker-detail/broker-detail.html',0,import13.ViewEncapsulation.None,styles_BrokerDetailPage,{})); }
  return new _View_BrokerDetailPage0(viewUtils,parentInjector,declarationEl);
}