/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/platform/platform';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from 'ionic-angular/components/menu/menu';
import * as import13 from 'ionic-angular/components/content/content';
import * as import14 from 'ionic-angular/components/list/list';
import * as import15 from 'ionic-angular/components/item/item';
import * as import16 from 'ionic-angular/components/list/list-header';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from 'ionic-angular/components/nav/nav';
import * as import19 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import20 from 'ionic-angular/components/menu/menu-controller';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from 'ionic-angular/util/keyboard';
import * as import24 from '@angular/core/src/zone/ng_zone';
import * as import25 from 'ionic-angular/gestures/gesture-controller';
import * as import26 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/navigation/view-controller';
import * as import29 from 'ionic-angular/components/tabs/tabs';
import * as import30 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import31 from 'ionic-angular/util/form';
import * as import32 from '@angular/core/src/linker/template_ref';
import * as import33 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import34 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import35 from 'ionic-angular/navigation/nav-controller-base';
import * as import36 from '@angular/core/src/linker/component_factory_resolver';
import * as import37 from 'ionic-angular/transitions/transition-controller';
import * as import38 from 'ionic-angular/navigation/deep-linker';
import * as import39 from 'ionic-angular/components/menu/menu-close';
import * as import40 from 'ionic-angular/components/icon/icon';
var renderType_MyApp_Host:import0.RenderComponentType = (null as any);
class _View_MyApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MyApp_0_4:import3.MyApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp_Host0,renderType_MyApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyApp_0_4 = new import3.MyApp(this.parentInjector.get(import8.Platform));
    this._appEl_0.initComponent(this._MyApp_0_4,[],compView_0);
    compView_0.create(this._MyApp_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MyApp) && (0 === requestNodeIndex))) { return this._MyApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_MyApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MyApp_Host === (null as any))) { (renderType_MyApp_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_MyApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyAppNgFactory:import10.ComponentFactory<import3.MyApp> = new import10.ComponentFactory<import3.MyApp>('ng-component',viewFactory_MyApp_Host0,import3.MyApp);
const styles_MyApp:any[] = [];
var renderType_MyApp:import0.RenderComponentType = (null as any);
class _View_MyApp0 extends import1.AppView<import3.MyApp> {
  _viewQuery_Nav_0:import11.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Menu_0_4:import12.Menu;
  _query_Content_0_0:import11.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Content_2_4:import13.Content;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _List_6_3:import14.List;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _Item_8_4:import15.Item;
  _ListHeader_8_5:import16.ListHeader;
  _query_Label_8_0:import11.QueryList<any>;
  _query_Button_8_1:import11.QueryList<any>;
  _query_Icon_8_2:import11.QueryList<any>;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgFor_11_6:import17.NgFor;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _List_14_3:import14.List;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _Item_16_4:import15.Item;
  _ListHeader_16_5:import16.ListHeader;
  _query_Label_16_0:import11.QueryList<any>;
  _query_Button_16_1:import11.QueryList<any>;
  _query_Icon_16_2:import11.QueryList<any>;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import17.NgFor;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _Nav_25_4:import18.Nav;
  _text_26:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp0,renderType_MyApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import11.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import19.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import12.Menu(this.parentInjector.get(import20.MenuController),new import21.ElementRef(this._el_0),this.parentInjector.get(import22.Config),this.parentInjector.get(import8.Platform),this.renderer,this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import24.NgZone),this.parentInjector.get(import25.GestureController));
    this._query_Content_0_0 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Menu_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import26.viewFactory_Content0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Content_2_4 = new import13.Content(this.parentInjector.get(import22.Config),new import21.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import24.NgZone),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import29.Tabs,(null as any)));
    this._appEl_2.initComponent(this._Content_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','menu-logo');
    this.renderer.setElementAttribute(this._el_4,'src','assets/img/Item.png');
    this._text_5 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_6_3 = new import14.List(this.parentInjector.get(import22.Config),new import21.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import25.GestureController));
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','item');
    this._appEl_8 = new import2.AppElement(8,6,this,this._el_8);
    var compView_8:any = import30.viewFactory_Item0(this.viewUtils,this.injector(8),this._appEl_8);
    this._Item_8_4 = new import15.Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import21.ElementRef(this._el_8),this.renderer);
    this._ListHeader_8_5 = new import16.ListHeader(this.parentInjector.get(import22.Config),this.renderer,new import21.ElementRef(this._el_8),(null as any));
    this._query_Label_8_0 = new import11.QueryList<any>();
    this._query_Button_8_1 = new import11.QueryList<any>();
    this._query_Icon_8_2 = new import11.QueryList<any>();
    this._appEl_8.initComponent(this._Item_8_4,[],compView_8);
    this._text_9 = this.renderer.createText((null as any),'\n        Allies\n      ',(null as any));
    this._query_Label_8_0.reset([]);
    this._Item_8_4.contentLabel = this._query_Label_8_0.first;
    compView_8.create(this._Item_8_4,[
      [],
      [],
      [].concat([this._text_9]),
      [],
      []
    ]
    ,(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_11 = new import2.AppElement(11,6,this,this._anchor_11);
    this._TemplateRef_11_5 = new import32.TemplateRef_(this._appEl_11,viewFactory_MyApp1);
    this._NgFor_11_6 = new import17.NgFor(this._appEl_11.vcRef,this._TemplateRef_11_5,this.parentInjector.get(import33.IterableDiffers),this.ref);
    this._text_12 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_14_3 = new import14.List(this.parentInjector.get(import22.Config),new import21.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import25.GestureController));
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','item');
    this._appEl_16 = new import2.AppElement(16,14,this,this._el_16);
    var compView_16:any = import30.viewFactory_Item0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Item_16_4 = new import15.Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import21.ElementRef(this._el_16),this.renderer);
    this._ListHeader_16_5 = new import16.ListHeader(this.parentInjector.get(import22.Config),this.renderer,new import21.ElementRef(this._el_16),(null as any));
    this._query_Label_16_0 = new import11.QueryList<any>();
    this._query_Button_16_1 = new import11.QueryList<any>();
    this._query_Icon_16_2 = new import11.QueryList<any>();
    this._appEl_16.initComponent(this._Item_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n        Help\n      ',(null as any));
    this._query_Label_16_0.reset([]);
    this._Item_16_4.contentLabel = this._query_Label_16_0.first;
    compView_16.create(this._Item_16_4,[
      [],
      [],
      [].concat([this._text_17]),
      [],
      []
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_19 = new import2.AppElement(19,14,this,this._anchor_19);
    this._TemplateRef_19_5 = new import32.TemplateRef_(this._appEl_19,viewFactory_MyApp2);
    this._NgFor_19_6 = new import17.NgFor(this._appEl_19.vcRef,this._TemplateRef_19_5,this.parentInjector.get(import33.IterableDiffers),this.ref);
    this._text_20 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_2.create(this._Content_2_4,[
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_5,
        this._el_6,
        this._text_13,
        this._el_14,
        this._text_21
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_0_0.reset([this._Content_2_4]);
    this._Menu_0_4.menuContent = this._query_Content_0_0.first;
      compView_0.create(this._Menu_0_4,[[].concat([
        this._text_1,
        this._el_2,
        this._text_22
      ]
    )],(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_24 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_25 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_25,'swipeBackEnabled','false');
    this._appEl_25 = new import2.AppElement(25,(null as any),this,this._el_25);
    var compView_25:any = import34.viewFactory_Nav0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Nav_25_4 = new import18.Nav(this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import35.NavControllerBase,(null as any)),this.parentInjector.get(import27.App),this.parentInjector.get(import22.Config),this.parentInjector.get(import23.Keyboard),new import21.ElementRef(this._el_25),this.parentInjector.get(import24.NgZone),this.renderer,this.parentInjector.get(import36.ComponentFactoryResolver),this.parentInjector.get(import25.GestureController),this.parentInjector.get(import37.TransitionController),this.parentInjector.get(import38.DeepLinker,(null as any)));
    this._appEl_25.initComponent(this._Nav_25_4,[],compView_25);
    compView_25.create(this._Nav_25_4,[],(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_25_4]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.Item) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Item_8_4; }
    if (((token === import16.ListHeader) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ListHeader_8_5; }
    if (((token === import32.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import17.NgFor) && (11 === requestNodeIndex))) { return this._NgFor_11_6; }
    if (((token === import14.List) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._List_6_3; }
    if (((token === import15.Item) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Item_16_4; }
    if (((token === import16.ListHeader) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ListHeader_16_5; }
    if (((token === import32.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import17.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6; }
    if (((token === import14.List) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._List_14_3; }
    if (((token === import13.Content) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Content_2_4; }
    if (((token === import12.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Menu_0_4; }
    if (((token === import18.Nav) && (25 === requestNodeIndex))) { return this._Nav_25_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changed = false;
    const currVal_0:any = this._Nav_25_4;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Menu_0_4.content = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Menu_0_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_2_4.ngOnInit(); }
    changes = (null as any);
    const currVal_2:any = this.context.appMenuItems;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_11_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_11_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_11_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_3:any = this.context.helpMenuItems;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_19_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_19_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_19_6.ngDoCheck(); }
    const currVal_4:any = this.context.rootPage;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Nav_25_4.root = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'false';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Nav_25_4.swipeBackEnabled = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_8_1.dirty) {
        this._query_Button_8_1.reset([]);
        this._Item_8_4._buttons = this._query_Button_8_1;
        this._query_Button_8_1.notifyOnChanges();
      }
      if (this._query_Icon_8_2.dirty) {
        this._query_Icon_8_2.reset([]);
        this._Item_8_4._icons = this._query_Icon_8_2;
        this._query_Icon_8_2.notifyOnChanges();
      }
      if (this._query_Button_16_1.dirty) {
        this._query_Button_16_1.reset([]);
        this._Item_16_4._buttons = this._query_Button_16_1;
        this._query_Button_16_1.notifyOnChanges();
      }
      if (this._query_Icon_16_2.dirty) {
        this._query_Icon_16_2.reset([]);
        this._Item_16_4._icons = this._query_Icon_16_2;
        this._query_Icon_16_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_8_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_16_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Content_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_25_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_2_4.ngOnDestroy();
    this._Menu_0_4.ngOnDestroy();
  }
}
export function viewFactory_MyApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MyApp> {
  if ((renderType_MyApp === (null as any))) { (renderType_MyApp = viewUtils.createRenderComponentType('C:/Users/guojin/Desktop/server/ivc/.tmp/app/app.html',0,import9.ViewEncapsulation.None,styles_MyApp,{})); }
  return new _View_MyApp0(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import15.Item;
  _ItemContent_0_5:import15.ItemContent;
  _MenuClose_0_6:import39.MenuClose;
  _query_Label_0_0:import11.QueryList<any>;
  _query_Button_0_1:import11.QueryList<any>;
  _query_Icon_0_2:import11.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import40.Icon;
  _text_3:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp1,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import30.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import15.Item(this.parent.parentInjector.get(import31.Form),this.parent.parentInjector.get(import22.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import15.ItemContent();
    this._MenuClose_0_6 = new import39.MenuClose(this.parent.parentInjector.get(import20.MenuController));
    this._query_Label_0_0 = new import11.QueryList<any>();
    this._query_Button_0_1 = new import11.QueryList<any>();
    this._query_Icon_0_2 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import40.Icon(this.parent.parentInjector.get(import22.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [].concat([this._el_2]),
      [],
      [].concat([
        this._text_1,
        this._text_3
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import15.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4; }
    if (((token === import15.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5; }
    if (((token === import39.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.$implicit.icon;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MyApp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp1(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import15.Item;
  _ItemContent_0_5:import15.ItemContent;
  _MenuClose_0_6:import39.MenuClose;
  _query_Label_0_0:import11.QueryList<any>;
  _query_Button_0_1:import11.QueryList<any>;
  _query_Icon_0_2:import11.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import40.Icon;
  _text_3:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp2,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import30.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import15.Item(this.parent.parentInjector.get(import31.Form),this.parent.parentInjector.get(import22.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import15.ItemContent();
    this._MenuClose_0_6 = new import39.MenuClose(this.parent.parentInjector.get(import20.MenuController));
    this._query_Label_0_0 = new import11.QueryList<any>();
    this._query_Button_0_1 = new import11.QueryList<any>();
    this._query_Icon_0_2 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import40.Icon(this.parent.parentInjector.get(import22.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [].concat([this._el_2]),
      [],
      [].concat([
        this._text_1,
        this._text_3
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import15.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4; }
    if (((token === import15.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5; }
    if (((token === import39.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.$implicit.icon;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MyApp2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp2(viewUtils,parentInjector,declarationEl);
}