let brokers = [
    {
        id: 1,
        firstName: "Nino",
        lastName: "F",//gender
        title: "Pious Mage",
        weapon: "Green Tome",
        unit:"Infantry",
        hp: 16,
        atk: 20,
        spd: 10,
        def: 4,
        res: 7,
        hpm: 33,
        atkm: 46,
        spdm: 36,
        defm: 19,
        resm: 29,
        artby: "Amagaitaro (アマガイタロー)",
        skills: {
            skillA: "Resistance",
            skillB: "HP",
            skillC: "Hone Atk"
        },
        skillA: "Resistance",
        skillB: "HP",
        skillC: "Hone Atk",           
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Nino.png"
    },
    {
        id: 2,
        firstName: "Lucina",
        lastName: "F",
        title: "Future Witness",
        hp: 19,
        atk: 24,
        spd: 10,
        def: 6,
        res: 4,
        hpm: 43,
        atkm: 50,
        spdm: 36,
        defm: 25,
        resm: 19,
        artby:"Maiponpon (まいぽんぽん)  / INTELLIGENT SYSTEMS",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "michael@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Lucina.png"
    },
    {
        id: 3,
        firstName: "Hector",
        lastName: "M",
        title: "General of Ostia",
        hp: 24,
        atk: 26,
        spd: 5,
        def: 11,
        res: 4,
        hpm: 52,
        atkm: 52,
        spdm: 24,
        defm: 37,
        resm: 19,
        artby: "AKIRA",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "jonathan@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Hector_0.png"
    },
    {
        id: 4,
        firstName: "Takumi",
        lastName: "M",
        title: "Wild Card",
        hp: 18,
        atk: 22,
        spd: 7,
        def: 6,
        res: 5,
        hpm: 40,
        atkm: 46,
        spdm: 33,
        defm: 25,
        resm: 18,
        artby: "Hino Shinnosuke (日野慎之助)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "jen@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Takumi.png"
    },
    {
        id: 5,
        firstName: "Linde",
        lastName: "F",
        title: "Light Mage",
        hp: 16,
        atk: 23,
        spd: 10,
        def: 4,
        res: 5,
        hpm: 35,
        atkm: 49,
        spdm: 39,
        defm: 14,
        resm: 27,
        artby: "Kippu (切符)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "olivia@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Linde.png"
    },
    {
        id: 6,
        firstName: "Ninian",
        lastName: "F",
        title: "Oracle of Destiny",
        hp: 16,
        atk: 18,
        spd: 7,
        def: 6,
        res: 5,
        hpm: 42,
        atkm: 37,
        spdm: 33,
        defm: 23,
        resm: 27,
        artby: "Kippu (切符)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "miriam@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-03/Ninian.png"
    },
    {
        id: 7,
        firstName: "Jaffar",
        lastName: "M",
        title: "Angel of Death",
        hp: 17,
        atk: 18,
        spd: 9,
        def: 6,
        res: 5,
        hpm: 41,
        atkm: 42,
        spdm: 38,
        defm: 20,
        resm: 17,
        artby: "Kusugi Toku (久杉トク)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "michelle@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-03/Jaffar.png"
    },
    {
        id: 8,
        firstName: "Tharja",
        lastName: "F",
        title: "Dark Shadow",
        hp: 17,
        atk: 21,
        spd: 8,
        def: 6,
        res: 5,
        hpm: 39,
        atkm: 45,
        spdm: 34,
        defm: 23,
        resm: 20,
        artby: "ZIS",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Tharja.png"
    },
    {
        id: 9,
        firstName: "Effie",
        lastName: "F",
        title: "Army of One",
        hp: 22,
        atk: 27,
        spd: 5,
        def: 11,
        res: 4,
        hpm: 50,
        atkm: 55,
        spdm: 22,
        defm: 33,
        resm: 23,
        artby: "HACCAN",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Effie.png"
    },
    {
        id: 10,
        firstName: "Elise",
        lastName: "F",
        title: "Budding Flower",
        hp: 15,
        atk: 18,
        spd: 8,
        def: 4,
        res: 8,
        hpm: 30,
        atkm: 42,
        spdm: 32,
        defm: 19,
        resm: 32,
        artby: "HAKO (羽公)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Elise.png"
    },
    {
        id: 11,
        firstName: "Azura",
        lastName: "F",
        title: "Lady of the Lake",
        hp: 17,
        atk: 17,
        spd: 7,
        def: 4,
        res: 6,
        hpm: 36,
        atkm: 43,
        spdm: 36,
        defm: 21,
        resm: 28,
        artby: "kaya8",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Azura.png"
    },
    {
        id: 12,
        firstName: "Camilla",
        lastName: "F",
        title: "Bewitching Beauty",
        hp: 18,
        atk: 16,
        spd: 3,
        def: 6,
        res: 7,
        hpm: 37,
        atkm: 38,
        spdm: 27,
        defm: 28,
        resm: 31,
        artby: "Maeshima Shigeki (前嶋重機)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Camilla.png"
    },
    {
        id: 13,
        firstName: "Catria",
        lastName: "F",
        title: "Middle Whitewing",
        hp: 17,
        atk: 18,
        spd: 10,
        def: 7,
        res: 6,
        hpm: 39,
        atkm: 42,
        spdm: 34,
        defm: 29,
        resm: 25,
        artby: "Amagaitaro (アマガイタロー)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Catria.png"
    },
    {
        id: 14,
        firstName: "Eirika",
        lastName: "F",
        title: "Restoration Lady",
        hp: 18,
        atk: 23,
        spd: 9,
        def: 7,
        res: 6,
        hpm: 42,
        atkm: 42,
        spdm: 35,
        defm: 26,
        resm: 28,
        artby: "Asatani Tomoyo (麻谷知世)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Eirika.png"
    },
    {
        id: 15,
        firstName: "Eliwood",
        lastName: "M",
        title: "Knight of Lycia",
        hp: 17,
        atk: 18,
        spd: 8,
        def: 6,
        res: 8,
        hpm: 39,
        atkm: 47,
        spdm: 30,
        defm: 23,
        resm: 32,
        artby: "Miyuu (深遊)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Eliwood.png"
    }, 
    {
        id: 16,
        firstName: "Gordin",
        lastName: "M",
        title: "Altean Archer",
        hp: 19,
        atk: 14,
        spd: 1,
        def: 8,
        res: 4,
        hpm: 43,
        atkm: 41,
        spdm: 20,
        defm: 32,
        resm: 17,
        artby: "Itagaki Hako (板垣ハコ)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Gordin.png"
    },
    {
        id: 17,
        firstName: "Selena",
        lastName: "F",
        title: "Cutting Wit",
        hp: 18,
        atk: 18,
        spd: 9,
        def: 8,
        res: 6,
        hpm: 37,
        atkm: 37,
        spdm: 35,
        defm: 32,
        resm: 28,
        artby: "Zaza (ザザ)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Selena.png"
    },
    {
        id: 18,
        firstName: "Minerva",
        lastName: "F",
        title: "Red Dragon",
        hp: 18,
        atk: 23,
        spd: 9,
        def: 8,
        res: 5,
        hpm: 40,
        atkm: 52,
        spdm: 38,
        defm: 27,
        resm: 17,
        artby: "Daisuke Izuka",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Minerva.png"
    },
    {
        id: 19,
        firstName: "Klein",
        lastName: "M",
        title: "Silver Nobleman",
        hp: 18,
        atk: 16,
        spd: 2,
        def: 5,
        res: 5,
        hpm: 40,
        atkm: 38,
        spdm: 28,
        defm: 20,
        resm: 24,
        artby: "Tobi",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Klein.png"
    },
    {
        id: 20,
        firstName: "Merric",
        lastName: "M",
        title: "Wind Mage",
        hp: 19,
        atk: 21,
        spd: 8,
        def: 6,
        res: 4,
        hpm: 48,
        atkm: 40,
        spdm: 32,
        defm: 28,
        resm: 19,
        artby: "Mizuno Kana (水野加奈)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Merric.png"
    },
    {
        id: 21,
        firstName: "Kagero",
        lastName: "F",
        title: "Honorable Ninja",
        hp: 16,
        atk: 14,
        spd: 8,
        def: 5,
        res: 6,
        hpm: 31,
        atkm: 40,
        spdm: 32,
        defm: 22,
        resm: 28,
        artby: "lack",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Kagero.png"
    },
    {
        id: 22,
        firstName: "Jakob",
        lastName: "M",
        title: "Devoted Servant",
        hp: 17,
        atk: 17,
        spd: 9,
        def: 6,
        res: 5,
        hpm: 39,
        atkm: 39,
        spdm: 31,
        defm: 28,
        resm: 24,
        artby: "Fujisaka Kimihiko (藤坂公彦)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Jakob.png"
    },
    {
        id: 23,
        firstName: "Leo",
        lastName: "M",
        title: "Sorcerous Prince",
        hp: 17,
        atk: 21,
        spd: 5,
        def: 6,
        res: 8,
        hpm: 39,
        atkm: 43,
        spdm: 22,
        defm: 25,
        resm: 30,
        artby: "Hino Shinnosuke (日野慎之助)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Leo.png"
    },
    {
        id: 24,
        firstName: "Ephraim",
        lastName: "M",
        title: "Restoration Lord",
        hp: 19,
        atk: 25,
        spd: 6,
        def: 8,
        res: 5,
        hpm: 45,
        atkm: 51,
        spdm: 25,
        defm: 32,
        resm: 20,
        artby: "Asatani Tomoyo (麻谷知世)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Ephraim.png"
    },
    {
        id: 25,
        firstName: "Chrom",
        lastName: "M",
        title: "Exalted Prince",
        hp: 21,
        atk: 25,
        spd: 6,
        def: 7,
        res: 4,
        hpm: 47,
        atkm: 53,
        spdm: 25,
        defm: 31,
        resm: 17,
        artby: "Ebila (えびら)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Chrom.png"
    },
    {
        id: 26,
        firstName: "Cain",
        lastName: "M",
        title: "The Bull",
        hp: 18,
        atk: 16,
        spd: 1,
        def: 8,
        res: 6,
        hpm: 42,
        atkm: 40,
        spdm: 27,
        defm: 27,
        resm: 21,
        artby: "Meka (めか)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Cain.png"
    },
    {
        id: 27,
        firstName: "Caeda",
        lastName: "F",
        title: "Talys's Heart",
        hp: 17,
        atk: 18,
        spd: 9,
        def: 5,
        res: 10,
        hpm: 36,
        atkm: 37,
        spdm: 37,
        defm: 24,
        resm: 34,
        artby: "HAKO (羽公)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Caeda.png"
    },
    {
        id: 28,
        firstName: "Corrin",
        lastName: "F",
        title: "Fateful Princess",
        hp: 19,
        atk: 21,
        spd: 6,
        def: 8,
        res: 6,
        hpm: 41,
        atkm: 40,
        spdm: 34,
        defm: 34,
        resm: 21,
        artby: "bthx",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Corrin-F.png"
    },
    {
        id: 29,
        firstName: "Clarine",
        lastName: "F",
        title: "Refined Noble",
        hp: 16,
        atk: 16,
        spd: 9,
        def: 5,
        res: 7,
        hpm: 35,
        atkm: 35,
        spdm: 33,
        defm: 22,
        resm: 32,
        artby: "Amagaitaro (アマガイタロー)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Clarine.png"
    },
    {
        id: 30,
        firstName: "Hinoka",
        lastName: "F",
        title: "Warrior Princess",
        hp: 19,
        atk: 15,
        spd: 3,
        def: 6,
        res: 7,
        hpm: 41,
        atkm: 43,
        spdm: 27,
        defm: 25,
        resm: 24,
        artby: "HACCAN",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Hinoka.png"
    },
    {
        id: 31,
        firstName: "Tiki",
        lastName: "F",
        title: "Dragon Scion",
        hp: 15,
        atk: 20,
        spd: 4,
        def: 8,
        res: 7,
        hpm: 41,
        atkm: 46,
        spdm: 30,
        defm: 32,
        resm: 29,
        artby: "Ito Noizi (いとうのいぢ)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Tiki-%28Young%29.png"
    },
    {
        id: 32,
        firstName: "Tiki",
        lastName: "M",
        title: "Naga's Voice",
        hp: 18,
        atk: 18,
        spd: 6,
        def: 9,
        res: 7,
        hpm: 40,
        atkm: 46,
        spdm: 23,
        defm: 35,
        resm: 24,
        artby: "Ito Noizi (いとうのいぢ)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Tiki-Adult.png"
    },
    {
        id: 33,
        firstName: "Nowi",
        lastName: "F",
        title: "Eternal Youth",
        hp: 17,
        atk: 17,
        spd: 5,
        def: 6,
        res: 5,
        hpm: 45,
        atkm: 45,
        spdm: 27,
        defm: 33,
        resm: 27,
        artby: "lack",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Nowi.png"
    },
    {
        id: 34,
        firstName: "Fae",
        lastName: "F",
        title: "Divine Dragon",
        hp: 16,
        atk: 18,
        spd: 4,
        def: 6,
        res: 8,
        hpm: 46,
        atkm: 46,
        spdm: 28,
        defm: 25,
        resm: 30,
        artby: "Himukai Yuji (日向悠二)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Fae.png"
    },
    {
        id: 35,
        firstName: "Corrin",
        lastName: "M",
        title: "Fateful Prince",
        hp: 20,
        atk: 24,
        spd: 8,
        def: 6,
        res: 5,
        hpm: 42,
        atkm: 48,
        spdm: 32,
        defm: 31,
        resm: 24,
        artby: "Maiponpon (まいぽんぽん)  / INTELLIGENT SYSTEMS",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Corrin-M.png"
    },
    {
        id: 36,
        firstName: "Lyn",
        lastName: "F",
        title: "Lady of the Plains",
        hp: 18,
        atk: 22,
        spd: 11,
        def: 7,
        res: 5,
        hpm: 37,
        atkm: 44,
        spdm: 37,
        defm: 26,
        resm: 29,
        artby: "Yamada Kotaro (山田孝太郎)",
        phone: "617-244-3672",
        mobilePhone: "617-244-3672",
        email: "victor@ionicrealty.com",
        avatar_url: "http://fireemblem.gamepress.gg/sites/fireemblem.gamepress.gg/files/2017-02/Lyn.png"
    }
];

export default brokers;
