/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './property-detail';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from 'ionic-angular/navigation/nav-params';
import * as import11 from '../../providers/property-service-mock';
import * as import12 from 'ionic-angular/components/toast/toast';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from 'ionic-angular/components/toolbar/toolbar';
import * as import16 from 'ionic-angular/components/navbar/navbar';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from '@angular/common/src/directives/ng_if';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/navigation/view-controller';
import * as import23 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import24 from 'ionic-angular/components/app/app';
import * as import25 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/components/tabs/tabs';
import * as import30 from '@angular/core/src/linker/template_ref';
import * as import31 from 'ionic-angular/components/card/card';
import * as import32 from 'ionic-angular/components/list/list';
import * as import33 from 'ionic-angular/components/item/item';
import * as import34 from '@angular/core/src/linker/query_list';
import * as import35 from 'ionic-angular/components/icon/icon';
import * as import36 from 'ionic-angular/components/note/note';
import * as import37 from 'ionic-angular/components/avatar/avatar';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/gestures/gesture-controller';
import * as import40 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import41 from 'ionic-angular/util/form';
import * as import42 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import43 from '@angular/core/src/security';
var renderType_PropertyDetailPage_Host:import0.RenderComponentType = (null as any);
class _View_PropertyDetailPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PropertyDetailPage_0_4:import3.PropertyDetailPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PropertyDetailPage_Host0,renderType_PropertyDetailPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-property-detail',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PropertyDetailPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PropertyDetailPage_0_4 = new import3.PropertyDetailPage(this.parentInjector.get(import8.ActionSheetController),this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.NavParams),this.parentInjector.get(import11.PropertyService),this.parentInjector.get(import12.ToastController));
    this._appEl_0.initComponent(this._PropertyDetailPage_0_4,[],compView_0);
    compView_0.create(this._PropertyDetailPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PropertyDetailPage) && (0 === requestNodeIndex))) { return this._PropertyDetailPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_PropertyDetailPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PropertyDetailPage_Host === (null as any))) { (renderType_PropertyDetailPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_PropertyDetailPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PropertyDetailPageNgFactory:import14.ComponentFactory<import3.PropertyDetailPage> = new import14.ComponentFactory<import3.PropertyDetailPage>('page-property-detail',viewFactory_PropertyDetailPage_Host0,import3.PropertyDetailPage);
const styles_PropertyDetailPage:any[] = [];
var renderType_PropertyDetailPage:import0.RenderComponentType = (null as any);
class _View_PropertyDetailPage0 extends import1.AppView<import3.PropertyDetailPage> {
  _el_0:any;
  _Header_0_3:import15.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import16.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import17.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import18.Content;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import19.NgIf;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PropertyDetailPage0,renderType_PropertyDetailPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Header(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import22.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import23.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Navbar(this.parentInjector.get(import24.App),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import25.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.ToolbarTitle(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import15.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Property',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import26.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import18.Content(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import24.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import29.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_11 = new import2.AppElement(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import30.TemplateRef_(this._appEl_11,viewFactory_PropertyDetailPage1);
    this._NgIf_11_6 = new import19.NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._appEl_11,
        this._text_12
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import16.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import15.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import30.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import19.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6; }
    if (((token === import18.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_3:any = this.context.property.id;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_11_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
  }
}
export function viewFactory_PropertyDetailPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PropertyDetailPage> {
  if ((renderType_PropertyDetailPage === (null as any))) { (renderType_PropertyDetailPage = viewUtils.createRenderComponentType('C:/Users/guojin/Desktop/server/ivc/.tmp/pages/property-detail/property-detail.html',0,import13.ViewEncapsulation.None,styles_PropertyDetailPage,{})); }
  return new _View_PropertyDetailPage0(viewUtils,parentInjector,declarationEl);
}
class _View_PropertyDetailPage1 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import31.Card;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _CardContent_4_3:import31.CardContent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _List_13_3:import32.List;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _Item_15_4:import33.Item;
  _ItemContent_15_5:import33.ItemContent;
  _query_Label_15_0:import34.QueryList<any>;
  _query_Button_15_1:import34.QueryList<any>;
  _query_Icon_15_2:import34.QueryList<any>;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import35.Icon;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _Note_22_3:import36.Note;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _Item_26_4:import33.Item;
  _ItemContent_26_5:import33.ItemContent;
  _query_Label_26_0:import34.QueryList<any>;
  _query_Button_26_1:import34.QueryList<any>;
  _query_Icon_26_2:import34.QueryList<any>;
  _text_27:any;
  _el_28:any;
  _Icon_28_3:import35.Icon;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _Note_33_3:import36.Note;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _Item_37_4:import33.Item;
  _ItemContent_37_5:import33.ItemContent;
  _query_Label_37_0:import34.QueryList<any>;
  _query_Button_37_1:import34.QueryList<any>;
  _query_Icon_37_2:import34.QueryList<any>;
  _text_38:any;
  _el_39:any;
  _Icon_39_3:import35.Icon;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _Note_44_3:import36.Note;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  /*private*/ _appEl_48:import2.AppElement;
  _Item_48_4:import33.Item;
  _ItemContent_48_5:import33.ItemContent;
  _query_Label_48_0:import34.QueryList<any>;
  _query_Button_48_1:import34.QueryList<any>;
  _query_Icon_48_2:import34.QueryList<any>;
  _text_49:any;
  _el_50:any;
  _Avatar_50_3:import37.Avatar;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  /*private*/ _appEl_63:import2.AppElement;
  _Item_63_4:import33.Item;
  _ItemContent_63_5:import33.ItemContent;
  _query_Label_63_0:import34.QueryList<any>;
  _query_Button_63_1:import34.QueryList<any>;
  _query_Icon_63_2:import34.QueryList<any>;
  _text_64:any;
  _el_65:any;
  /*private*/ _appEl_65:import2.AppElement;
  _Button_65_4:import38.Button;
  _text_66:any;
  _el_67:any;
  _Icon_67_3:import35.Icon;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  /*private*/ _appEl_70:import2.AppElement;
  _Button_70_4:import38.Button;
  _text_71:any;
  _el_72:any;
  _Icon_72_3:import35.Icon;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PropertyDetailPage1,renderType_PropertyDetailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_0_3 = new import31.Card(this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this._CardContent_4_3 = new import31.CardContent();
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h2',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','card-title');
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'p',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'ion-list',(null as any));
    this._List_13_3 = new import32.List(this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_13),this.renderer,this.parent.parentInjector.get(import39.GestureController));
    this._text_14 = this.renderer.createText(this._el_13,'\n\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','item item-block');
    this._appEl_15 = new import2.AppElement(15,13,this,this._el_15);
    var compView_15:any = import40.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import33.Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_15),this.renderer);
    this._ItemContent_15_5 = new import33.ItemContent();
    this._query_Label_15_0 = new import34.QueryList<any>();
    this._query_Button_15_1 = new import34.QueryList<any>();
    this._query_Icon_15_2 = new import34.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4,[],compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_17,'item-left','');
    this.renderer.setElementAttribute(this._el_17,'name','moon');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import35.Icon(this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Bedrooms',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_22,'item-right','');
    this._Note_22_3 = new import36.Note();
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_15_0.reset([]);
    this._Item_15_4.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4,[
      [].concat([this._el_17]),
      [],
      [].concat([
        this._text_16,
        this._text_18,
        this._el_19,
        this._text_21,
        this._text_24
      ]
      ),
      [],
      [].concat([this._el_22])
    ]
    ,(null as any));
    this._text_25 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','item item-block');
    this._appEl_26 = new import2.AppElement(26,13,this,this._el_26);
    var compView_26:any = import40.viewFactory_Item0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Item_26_4 = new import33.Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_26),this.renderer);
    this._ItemContent_26_5 = new import33.ItemContent();
    this._query_Label_26_0 = new import34.QueryList<any>();
    this._query_Button_26_1 = new import34.QueryList<any>();
    this._query_Icon_26_2 = new import34.QueryList<any>();
    this._appEl_26.initComponent(this._Item_26_4,[],compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_28,'item-left','');
    this.renderer.setElementAttribute(this._el_28,'name','leaf');
    this.renderer.setElementAttribute(this._el_28,'role','img');
    this._Icon_28_3 = new import35.Icon(this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Bathrooms',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_33,'item-right','');
    this._Note_33_3 = new import36.Note();
    this._text_34 = this.renderer.createText(this._el_33,'',(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_26_0.reset([]);
    this._Item_26_4.contentLabel = this._query_Label_26_0.first;
    compView_26.create(this._Item_26_4,[
      [].concat([this._el_28]),
      [],
      [].concat([
        this._text_27,
        this._text_29,
        this._el_30,
        this._text_32,
        this._text_35
      ]
      ),
      [],
      [].concat([this._el_33])
    ]
    ,(null as any));
    this._text_36 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','item item-block');
    this._appEl_37 = new import2.AppElement(37,13,this,this._el_37);
    var compView_37:any = import40.viewFactory_Item0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Item_37_4 = new import33.Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_37),this.renderer);
    this._ItemContent_37_5 = new import33.ItemContent();
    this._query_Label_37_0 = new import34.QueryList<any>();
    this._query_Button_37_1 = new import34.QueryList<any>();
    this._query_Icon_37_2 = new import34.QueryList<any>();
    this._appEl_37.initComponent(this._Item_37_4,[],compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_39,'item-left','');
    this.renderer.setElementAttribute(this._el_39,'name','pricetag');
    this.renderer.setElementAttribute(this._el_39,'role','img');
    this._Icon_39_3 = new import35.Icon(this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_39),this.renderer);
    this._text_40 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Asking Price',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_44,'item-right','');
    this._Note_44_3 = new import36.Note();
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_37_0.reset([]);
    this._Item_37_4.contentLabel = this._query_Label_37_0.first;
    compView_37.create(this._Item_37_4,[
      [].concat([this._el_39]),
      [],
      [].concat([
        this._text_38,
        this._text_40,
        this._el_41,
        this._text_43,
        this._text_46
      ]
      ),
      [],
      [].concat([this._el_44])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','item item-block');
    this.renderer.setElementAttribute(this._el_48,'ion-item','');
    this._appEl_48 = new import2.AppElement(48,13,this,this._el_48);
    var compView_48:any = import40.viewFactory_Item0(this.viewUtils,this.injector(48),this._appEl_48);
    this._Item_48_4 = new import33.Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_48),this.renderer);
    this._ItemContent_48_5 = new import33.ItemContent();
    this._query_Label_48_0 = new import34.QueryList<any>();
    this._query_Button_48_1 = new import34.QueryList<any>();
    this._query_Icon_48_2 = new import34.QueryList<any>();
    this._appEl_48.initComponent(this._Item_48_4,[],compView_48);
    this._text_49 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_50,'item-left','');
    this._Avatar_50_3 = new import37.Avatar();
    this._text_51 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_50,'img',(null as any));
    this._text_53 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'',(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_58 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'',(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_48_0.reset([]);
    this._Item_48_4.contentLabel = this._query_Label_48_0.first;
    compView_48.create(this._Item_48_4,[
      [].concat([this._el_50]),
      [],
      [].concat([
        this._text_49,
        this._text_54,
        this._el_55,
        this._text_57,
        this._el_58,
        this._text_60
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_61 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_62 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_63,'class','item item-block');
    this._appEl_63 = new import2.AppElement(63,0,this,this._el_63);
    var compView_63:any = import40.viewFactory_Item0(this.viewUtils,this.injector(63),this._appEl_63);
    this._Item_63_4 = new import33.Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_63),this.renderer);
    this._ItemContent_63_5 = new import33.ItemContent();
    this._query_Label_63_0 = new import34.QueryList<any>();
    this._query_Button_63_1 = new import34.QueryList<any>();
    this._query_Icon_63_2 = new import34.QueryList<any>();
    this._appEl_63.initComponent(this._Item_63_4,[],compView_63);
    this._text_64 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_65 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_65,'clear','');
    this.renderer.setElementAttribute(this._el_65,'icon-left','');
    this.renderer.setElementAttribute(this._el_65,'ion-button','');
    this.renderer.setElementAttribute(this._el_65,'item-left','');
    this._appEl_65 = new import2.AppElement(65,63,this,this._el_65);
    var compView_65:any = import42.viewFactory_Button0(this.viewUtils,this.injector(65),this._appEl_65);
    this._Button_65_4 = new import38.Button((null as any),'',this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_65),this.renderer);
    this._appEl_65.initComponent(this._Button_65_4,[],compView_65);
    this._text_66 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_67 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_67,'name','star');
    this.renderer.setElementAttribute(this._el_67,'role','img');
    this._Icon_67_3 = new import35.Icon(this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_67),this.renderer);
    this._text_68 = this.renderer.createText((null as any),'\n                Favorite\n            ',(null as any));
      compView_65.create(this._Button_65_4,[[].concat([
        this._text_66,
        this._el_67,
        this._text_68
      ]
    )],(null as any));
    this._text_69 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_70 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_70,'clear','');
    this.renderer.setElementAttribute(this._el_70,'icon-left','');
    this.renderer.setElementAttribute(this._el_70,'ion-button','');
    this.renderer.setElementAttribute(this._el_70,'item-right','');
    this._appEl_70 = new import2.AppElement(70,63,this,this._el_70);
    var compView_70:any = import42.viewFactory_Button0(this.viewUtils,this.injector(70),this._appEl_70);
    this._Button_70_4 = new import38.Button((null as any),'',this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_70),this.renderer);
    this._appEl_70.initComponent(this._Button_70_4,[],compView_70);
    this._text_71 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_72 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_72,'name','share');
    this.renderer.setElementAttribute(this._el_72,'role','img');
    this._Icon_72_3 = new import35.Icon(this.parent.parentInjector.get(import20.Config),new import21.ElementRef(this._el_72),this.renderer);
    this._text_73 = this.renderer.createText((null as any),'\n                Share\n            ',(null as any));
      compView_70.create(this._Button_70_4,[[].concat([
        this._text_71,
        this._el_72,
        this._text_73
      ]
    )],(null as any));
    this._text_74 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_63_0.reset([]);
    this._Item_63_4.contentLabel = this._query_Label_63_0.first;
    compView_63.create(this._Item_63_4,[
      [].concat([this._el_65]),
      [],
      [].concat([
        this._text_64,
        this._text_69,
        this._text_74
      ]
      ),
      [],
      [].concat([this._el_70])
    ]
    ,(null as any));
    this._text_75 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_48,'click',this.eventHandler(this._handle_click_48_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_65,'click',this.eventHandler(this._handle_click_65_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_70,'click',this.eventHandler(this._handle_click_70_0.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.CardContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._CardContent_4_3; }
    if (((token === import35.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3; }
    if (((token === import36.Note) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Note_22_3; }
    if (((token === import33.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Item_15_4; }
    if (((token === import33.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._ItemContent_15_5; }
    if (((token === import35.Icon) && (28 === requestNodeIndex))) { return this._Icon_28_3; }
    if (((token === import36.Note) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Note_33_3; }
    if (((token === import33.Item) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Item_26_4; }
    if (((token === import33.ItemContent) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ItemContent_26_5; }
    if (((token === import35.Icon) && (39 === requestNodeIndex))) { return this._Icon_39_3; }
    if (((token === import36.Note) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Note_44_3; }
    if (((token === import33.Item) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Item_37_4; }
    if (((token === import33.ItemContent) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ItemContent_37_5; }
    if (((token === import37.Avatar) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Avatar_50_3; }
    if (((token === import33.Item) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Item_48_4; }
    if (((token === import33.ItemContent) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._ItemContent_48_5; }
    if (((token === import32.List) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._List_13_3; }
    if (((token === import35.Icon) && (67 === requestNodeIndex))) { return this._Icon_67_3; }
    if (((token === import38.Button) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Button_65_4; }
    if (((token === import35.Icon) && (72 === requestNodeIndex))) { return this._Icon_72_3; }
    if (((token === import38.Button) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Button_70_4; }
    if (((token === import33.Item) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._Item_63_4; }
    if (((token === import33.ItemContent) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._ItemContent_63_5; }
    if (((token === import31.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Card_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const currVal_3:any = 'moon';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_17_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_6:any = 'leaf';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_28_3.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = 'pricetag';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Icon_39_3.name = currVal_9;
      this._expr_9 = currVal_9;
    }
    changed = false;
    const currVal_17:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._Button_65_4.clear = currVal_17;
      changed = true;
      this._expr_17 = currVal_17;
    }
    if (changed) { this._appEl_65.componentView.markAsCheckOnce(); }
    const currVal_18:any = 'star';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._Icon_67_3.name = currVal_18;
      this._expr_18 = currVal_18;
    }
    changed = false;
    const currVal_21:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._Button_70_4.clear = currVal_21;
      changed = true;
      this._expr_21 = currVal_21;
    }
    if (changed) { this._appEl_70.componentView.markAsCheckOnce(); }
    const currVal_22:any = 'share';
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._Icon_72_3.name = currVal_22;
      this._expr_22 = currVal_22;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset([]);
        this._Item_15_4._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset([this._Icon_17_3]);
        this._Item_15_4._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      if (this._query_Button_26_1.dirty) {
        this._query_Button_26_1.reset([]);
        this._Item_26_4._buttons = this._query_Button_26_1;
        this._query_Button_26_1.notifyOnChanges();
      }
      if (this._query_Icon_26_2.dirty) {
        this._query_Icon_26_2.reset([this._Icon_28_3]);
        this._Item_26_4._icons = this._query_Icon_26_2;
        this._query_Icon_26_2.notifyOnChanges();
      }
      if (this._query_Button_37_1.dirty) {
        this._query_Button_37_1.reset([]);
        this._Item_37_4._buttons = this._query_Button_37_1;
        this._query_Button_37_1.notifyOnChanges();
      }
      if (this._query_Icon_37_2.dirty) {
        this._query_Icon_37_2.reset([this._Icon_39_3]);
        this._Item_37_4._icons = this._query_Icon_37_2;
        this._query_Icon_37_2.notifyOnChanges();
      }
      if (this._query_Button_48_1.dirty) {
        this._query_Button_48_1.reset([]);
        this._Item_48_4._buttons = this._query_Button_48_1;
        this._query_Button_48_1.notifyOnChanges();
      }
      if (this._query_Icon_48_2.dirty) {
        this._query_Icon_48_2.reset([]);
        this._Item_48_4._icons = this._query_Icon_48_2;
        this._query_Icon_48_2.notifyOnChanges();
      }
      if (this._query_Button_63_1.dirty) {
        this._query_Button_63_1.reset([
          this._Button_65_4,
          this._Button_70_4
        ]
        );
        this._Item_63_4._buttons = this._query_Button_63_1;
        this._query_Button_63_1.notifyOnChanges();
      }
      if (this._query_Icon_63_2.dirty) {
        this._query_Icon_63_2.reset([]);
        this._Item_63_4._icons = this._query_Icon_63_2;
        this._query_Icon_63_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_15_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_26_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_37_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_48_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_65_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_70_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_63_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.property.pic,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import43.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.parent.context.property.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_7,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(3,'',this.parent.context.property.address,', ',this.parent.context.property.city,' ',this.parent.context.property.state,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Icon_17_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_17,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.parent.context.property.bedrooms,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_23,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_28_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_28,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'',this.parent.context.property.bathrooms,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_34,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_10:any = this._Icon_39_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_39,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = import4.interpolate(1,'',this.parent.context.property.price,'');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_45,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = import4.interpolate(1,'',this.parent.context.property.broker.picture,'');
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementProperty(this._el_52,'src',this.viewUtils.sanitizer.sanitize(import43.SecurityContext.URL,currVal_13));
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = import4.interpolate(1,'',this.parent.context.property.broker.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_56,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = import4.interpolate(1,'',this.parent.context.property.broker.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_59,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_19:any = this._Icon_67_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_67,'hide',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_23:any = this._Icon_72_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_72,'hide',currVal_23);
      this._expr_23 = currVal_23;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_17_3.ngOnDestroy();
    this._Icon_28_3.ngOnDestroy();
    this._Icon_39_3.ngOnDestroy();
    this._Icon_67_3.ngOnDestroy();
    this._Icon_72_3.ngOnDestroy();
  }
  private _handle_click_48_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openBrokerDetail(this.parent.context.property.broker)) !== false);
    return (true && pd_0);
  }
  private _handle_click_65_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.favorite(this.parent.context.property)) !== false);
    return (true && pd_0);
  }
  private _handle_click_70_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.share(this.parent.context.property)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PropertyDetailPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PropertyDetailPage1(viewUtils,parentInjector,declarationEl);
}