/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './welcome';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from 'ionic-angular/components/toolbar/toolbar';
import * as import11 from 'ionic-angular/components/navbar/navbar';
import * as import12 from 'ionic-angular/components/button/button';
import * as import13 from 'ionic-angular/components/menu/menu-toggle';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from 'ionic-angular/components/icon/icon';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from 'ionic-angular/components/slides/slides';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/navigation/view-controller';
import * as import23 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import24 from 'ionic-angular/components/app/app';
import * as import25 from 'ionic-angular/navigation/nav-controller';
import * as import26 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import27 from 'ionic-angular/components/menu/menu-controller';
import * as import28 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from '../../node_modules/ionic-angular/components/slides/slides.ngfactory';
var renderType_WelcomePage_Host:import0.RenderComponentType = (null as any);
class _View_WelcomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _WelcomePage_0_4:import3.WelcomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_WelcomePage_Host0,renderType_WelcomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-welcome',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_WelcomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._WelcomePage_0_4 = new import3.WelcomePage();
    this._appEl_0.initComponent(this._WelcomePage_0_4,[],compView_0);
    compView_0.create(this._WelcomePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.WelcomePage) && (0 === requestNodeIndex))) { return this._WelcomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_WelcomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_WelcomePage_Host === (null as any))) { (renderType_WelcomePage_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_WelcomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const WelcomePageNgFactory:import9.ComponentFactory<import3.WelcomePage> = new import9.ComponentFactory<import3.WelcomePage>('page-welcome',viewFactory_WelcomePage_Host0,import3.WelcomePage);
const styles_WelcomePage:any[] = [];
var renderType_WelcomePage:import0.RenderComponentType = (null as any);
class _View_WelcomePage0 extends import1.AppView<import3.WelcomePage> {
  _el_0:any;
  _Header_0_3:import10.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import11.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import12.Button;
  _MenuToggle_4_5:import13.MenuToggle;
  _ToolbarItem_4_6:import14.ToolbarItem;
  _query_Button_4_0:import15.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import16.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import17.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import18.Content;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _Slides_16_4:import19.Slides;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _Slide_18_4:import19.Slide;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _Slide_24_4:import19.Slide;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _Slide_30_4:import19.Slide;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  _map_0:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_WelcomePage0,renderType_WelcomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import10.Header(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import22.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import23.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import11.Navbar(this.parentInjector.get(import24.App),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import25.NavController,(null as any)),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import26.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import12.Button('','',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import13.MenuToggle(this.parentInjector.get(import27.MenuController),new import21.ElementRef(this._el_4),this.parentInjector.get(import22.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import14.ToolbarItem(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import10.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import15.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import16.Icon(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_4.create(this._Button_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import28.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import17.ToolbarTitle(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import10.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'Welcome',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'no-bounce','');
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import29.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import18.Content(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import24.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-slides',(null as any));
    this._appEl_16 = new import2.AppElement(16,14,this,this._el_16);
    var compView_16:any = import33.viewFactory_Slides0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Slides_16_4 = new import19.Slides(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_16),this.renderer);
    this._appEl_16.initComponent(this._Slides_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n\n        ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-slide',(null as any));
    this.renderer.setElementAttribute(this._el_18,'style','background-image: url(\'assets/img/slide_properties.png\')');
    this._appEl_18 = new import2.AppElement(18,16,this,this._el_18);
    var compView_18:any = import33.viewFactory_Slide0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Slide_18_4 = new import19.Slide(new import21.ElementRef(this._el_18),this._Slides_16_4);
    this._appEl_18.initComponent(this._Slide_18_4,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Hero IV detail page.',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_18.create(this._Slide_18_4,[[].concat([
        this._text_19,
        this._el_20,
        this._text_22
      ]
    )],(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n\n        ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-slide',(null as any));
    this.renderer.setElementAttribute(this._el_24,'style','background-image: url(\'assets/img/slide_brokers.png\')');
    this._appEl_24 = new import2.AppElement(24,16,this,this._el_24);
    var compView_24:any = import33.viewFactory_Slide0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Slide_24_4 = new import19.Slide(new import21.ElementRef(this._el_24),this._Slides_16_4);
    this._appEl_24.initComponent(this._Slide_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Check any hero you want!',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_24.create(this._Slide_24_4,[[].concat([
        this._text_25,
        this._el_26,
        this._text_28
      ]
    )],(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n\n        ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-slide',(null as any));
    this.renderer.setElementAttribute(this._el_30,'style','background-image: url(\'assets/img/slide_favorites.png\')');
    this._appEl_30 = new import2.AppElement(30,16,this,this._el_30);
    var compView_30:any = import33.viewFactory_Slide0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Slide_30_4 = new import19.Slide(new import21.ElementRef(this._el_30),this._Slides_16_4);
    this._appEl_30.initComponent(this._Slide_30_4,[],compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Enjoy Hero Arts!',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_30.create(this._Slide_30_4,[[].concat([
        this._text_31,
        this._el_32,
        this._text_34
      ]
    )],(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n\n    ',(null as any));
      compView_16.create(this._Slides_16_4,[[].concat([
        this._text_17,
        this._el_18,
        this._text_23,
        this._el_24,
        this._text_29,
        this._el_30,
        this._text_35
      ]
    )],(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_14.create(this._Content_14_4,[
      [],
      [].concat([
        this._text_15,
        this._el_16,
        this._text_36
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_37 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {pager: p0};
    });
    this._expr_8 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import12.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import13.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import14.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import17.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import11.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import10.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3; }
    if (((token === import19.Slide) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Slide_18_4; }
    if (((token === import19.Slide) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Slide_24_4; }
    if (((token === import19.Slide) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Slide_30_4; }
    if (((token === import19.Slides) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Slides_16_4; }
    if (((token === import18.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Content_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    changed = false;
    const currVal_8:any = this._map_0(true);
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Slides_16_4.options = currVal_8;
      changed = true;
      this._expr_8 = currVal_8;
    }
    if (changed) { this._appEl_16.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Slides_16_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Slide_18_4.ngOnDestroy();
    this._Slide_24_4.ngOnDestroy();
    this._Slide_30_4.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_WelcomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.WelcomePage> {
  if ((renderType_WelcomePage === (null as any))) { (renderType_WelcomePage = viewUtils.createRenderComponentType('C:/Users/guojin/Desktop/server/iv/.tmp/pages/welcome/welcome.html',0,import8.ViewEncapsulation.None,styles_WelcomePage,{})); }
  return new _View_WelcomePage0(viewUtils,parentInjector,declarationEl);
}